package simulation.network;

/**
 * Enum that defines all identifiers for network events
 * Task specific identifiers may be included as well
 */
public enum NetworkDiscreteEventId {
    NETWORK_EVENT_ID_NONE,

    NETWORK_EVENT_ID_RANDOM_START_INITIALIZE,
    NETWORK_EVENT_ID_SELF_PERIODIC,

    NETWORK_EVENT_ID_APP_RECEIVE,
    NETWORK_EVENT_ID_APP_UPDATE,
    NETWORK_EVENT_ID_APP_SEND,

    NETWORK_EVENT_ID_TRANSPORT_RECEIVE,
    NETWORK_EVENT_ID_TRANSPORT_SEND,

    NETWORK_EVENT_ID_NET_RECEIVE,
    NETWORK_EVENT_ID_NET_SEND,
    NETWORK_EVENT_ID_NET_MULTICAST,

    NETWORK_EVENT_ID_LINK_RECEIVE,
    NETWORK_EVENT_ID_LINK_SEND,
    NETWORK_EVENT_ID_LINK_CHECK_CHANNEL_STATUS,
    NETWORK_EVENT_ID_LINK_FORWARD_TO_PHY,
    NETWORK_EVENT_ID_LINK_WAIT_FOR_SENDING,

    NETWORK_EVENT_ID_PHY_RECEIVE_MESSAGE_START,
    NETWORK_EVENT_ID_PHY_RECEIVE_MESSAGE_END,
    NETWORK_EVENT_ID_PHY_RECEIVE_INTERFERENCE_START,
    NETWORK_EVENT_ID_PHY_RECEIVE_INTERFERENCE_END,
    NETWORK_EVENT_ID_PHY_RECEIVE_INTERRUPTION_DETECTED,
    NETWORK_EVENT_ID_PHY_SEND_START,
    NETWORK_EVENT_ID_PHY_SEND_END,
}
